### ISSUE TITLE
Windows使用CMD运行，中文乱码

### ISSUE THREAD

**Issue by evil0xxx** [chasingboy/dirsx#1]
![1](https://github.com/user-attachments/assets/6cb960f9-2da9-45e5-a26f-2e595caa6c4e)

**Comment by evil0xxx** [comment]
中文乱码

**Comment by chasingboy** [comment]
这是颜色颜色显示问题，感觉大家现在都使用 window11 了，颜色显示没有做好兼容，下个版本看看兼容一下。
或者师傅可以安装微软官方的新终端 window terminal(window11 默认终端)解决这个问题。
https://github.com/microsoft/terminal

**Comment by enomothem** [comment]
送你一条神奇的命令
reg add HKCU\Console /v VirtualTerminalLevel /t REG_DWORD /d 0x00000001 /f
不用谢
