### ISSUE TITLE
多URL扫描报错

### ISSUE THREAD

**Issue by hkdonline** [chasingboy/dirsx#4]
一百个以上URL扫描后报错..

`goroutine 2820827 [running]:
dirsx/common/httpx.(*Httpx).send_targets(...)
	/Users/kali/tools/dirsx/dirsx-go/common/httpx/httpx.go:388
dirsx/common/httpx.(*Httpx).threader(0xc043510410, 0x652aa5?, 0xc043586d20)
	/Users/kali/tools/dirsx/dirsx-go/common/httpx/httpx.go:418 +0x80a
created by dirsx/common/httpx.(*Httpx).Runner in goroutine 1
	/Users/kali/tools/dirsx/dirsx-go/common/httpx/httpx.go:465 +0x476
`
感觉可以边扫描边存入文件，以免错误的时候-o里面文件都没有生成。

**Comment by chasingboy** [comment]
@hkdonline 感谢师傅提出的建议，之前有考虑过“边扫描边存入文件”，不过在多URL扫描时也会发生“Too many open files”的问题。当时没有好的解决方式，现在1.5.1新版本增加了异常处理方式，可以输出错误发生前的结果，应该是有效的。

**Comment by hkdonline** [comment]
好的 感谢。
