### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by JackeyLov5** [chasingboy/dirsx#6]
师傅 看到你这个项目 感觉还不错准备用一下！
然后是否能一直维护呢
建议更新bypass403的功能感觉还是挺实用的

**Comment by chasingboy** [comment]
@JackeyLov5 感谢认可！一直都在更新和维护，bypass403 功能已经在写了，到时候可能会更新在 appsx 或 dirsx 中。

**Comment by JackeyLov5** [comment]
师傅 功能更新到这个项目了吗

**Comment by chasingboy** [comment]
已经更新到工具 appsx https://github.com/chasingboy/appsx
