### ISSUE TITLE
每次提交都会执行这两段

### ISSUE THREAD

**Issue by helGayhub233** [chasingboy/dirsx#7]
这两个探测信息是否有必要？已经设置好的字典均携带了这些内容
![1734077689123](https://github.com/user-attachments/assets/5fb8f757-a016-40de-8300-43baa37416c8)

**Comment by helGayhub233** [comment]
还有个问题就是如果字典比较大的情况下，必须等待全部扫描完成后才会统一打印结果，而不是过程中实时打印

**Comment by chasingboy** [comment]
这2次请求是作为过滤结果的对比，因为需要对结果进行过滤处理，所以等处理完再打印

**Comment by chasingboy** [comment]
@helGayhub233 感谢师傅的建议，dirsx 1.6.2 版本已经修改结果为实时打印

**Comment by helGayhub233** [comment]
感谢
